[package]
name = "readable-code"
version = "0.0.2"
entrypoint = "src/lib.typ"
authors = ["lentilus"]
license = "MIT"
description = "foo"
repository = "https://github.com/lentilus/readable-typst"
exclude = ["README.md"]
categories = ["utility"]
